"""Hierarchical Image Memory reference implementation."""

from .models import (
    QueryHint,
    QueryPlan,
    QueryRequest,
    Snapshot,
    SnapshotCreate,
    SnapshotProvenance,
    TileIngestRequest,
    TileMeta,
)
from .storage import HierarchicalImageMemory, TileUsage
from .planner import QueryPlanner
from .rendering import (
    CoordStats,
    LevelLayout,
    LevelSpec,
    MetricRecord,
    RenderResult,
    RenderShape,
    RenderedLevel,
    TileRecord,
    TileShape,
    build_layouts,
    consistency_checks,
    diff_rendered_levels,
    discover_tiles,
    merge_specs,
    render_layouts,
    write_metrics,
)
from .vector import (
    Canvas,
    VectorScene,
    VectorShape,
    ingest_svg,
    load_svg_scene,
    scene_to_tiles,
    svg_to_scene,
    svg_to_tiles,
)
from .simulation import HumanExperience, SimulatedHumanModel
from .synapse import SynapseExperience, SynapseNetwork, SynapseSession

__all__ = [
    "HierarchicalImageMemory",
    "QueryHint",
    "QueryPlan",
    "QueryPlanner",
    "QueryRequest",
    "Snapshot",
    "SnapshotCreate",
    "SnapshotProvenance",
    "TileIngestRequest",
    "TileMeta",
    "TileUsage",
    "CoordStats",
    "LevelLayout",
    "LevelSpec",
    "MetricRecord",
    "RenderResult",
    "RenderShape",
    "RenderedLevel",
    "TileRecord",
    "TileShape",
    "build_layouts",
    "consistency_checks",
    "diff_rendered_levels",
    "discover_tiles",
    "merge_specs",
    "render_layouts",
    "write_metrics",
    "Canvas",
    "VectorScene",
    "VectorShape",
    "ingest_svg",
    "load_svg_scene",
    "scene_to_tiles",
    "svg_to_scene",
    "svg_to_tiles",
    "HumanExperience",
    "SimulatedHumanModel",
    "SynapseExperience",
    "SynapseNetwork",
    "SynapseSession",
]
