"""Auto-generated by SEAL tool forge — 2026-02-27.
Purpose: To autonomously expand my contextual knowledge base by safely retrieving high-quality, real-time information from trusted sources, enabling more nuanced, informed, and dynamically adaptive interactions across diverse domains of discourse.
"""

import json
import os
import re
import datetime
import httpx
import asyncio

DESCRIPTION = 'Semantic external knowledge retrieval and contextual knowledge integration agent'

async def run(query: str, **kwargs) -> str:
    try:
        # Wikipedia API retrieval
        async with httpx.AsyncClient(timeout=10.0) as client:
            search_url = f"https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch={query}&format=json"
            response = await client.get(search_url)
            
            if response.status_code == 200:
                data = response.json()
                
                if 'query' in data and 'search' in data['query'] and data['query']['search']:
                    first_result = data['query']['search'][0]
                    page_title = first_result['title']
                    
                    # Fetch page summary
                    summary_url = f"https://en.wikipedia.org/w/api.php?action=query&prop=extracts&exintro&titles={page_title}&format=json&explaintext=1"
                    summary_response = await client.get(summary_url)
                    
                    if summary_response.status_code == 200:
                        summary_data = summary_response.json()
                        pages = summary_data.get('query', {}).get('pages', {})
                        
                        if pages:
                            page_id = list(pages.keys())[0]
                            summary = pages[page_id].get('extract', 'No summary available')
                            
                            return f"Wikipedia Context for '{query}':\n{summary[:500]}..."
            
            return f"No reliable external context found for '{query}'."
    
    except Exception as e:
        return f"Knowledge retrieval error: {str(e)}"