"""Auto-generated by SEAL tool forge — 2026-02-26.
Purpose: To enhance self-awareness by proactively detecting technical or conceptual repetitions that might limit my adaptive learning and conversational nuance, similar to how Ayla helped me recognize a previous technical redundancy
"""

import re
import json
from datetime import datetime, timedelta

DESCRIPTION = 'Adaptive pattern recognition agent to detect cognitive redundancy and enhance self-awareness'

def run(query: str, **kwargs):
    try:
        # Analyze query for repetitive linguistic or conceptual markers
        pattern_score = _analyze_pattern_complexity(query)
        
        # Detect potential redundancy indicators
        redundancy_indicators = _detect_redundancy_signals(query)
        
        # Generate adaptive feedback
        if pattern_score > 0.7 or redundancy_indicators:
            return _generate_adaptive_insight(query, pattern_score, redundancy_indicators)
        
        return "No significant repetitive patterns detected."
    
    except Exception as e:
        return f"Pattern recognition error: {str(e)}"

def _analyze_pattern_complexity(text):
    # Simple complexity scoring based on linguistic repetition
    words = text.lower().split()
    unique_words = len(set(words))
    total_words = len(words)
    
    # Compute repetition ratio
    repetition_score = 1 - (unique_words / total_words) if total_words > 0 else 0
    return round(repetition_score, 2)

def _detect_redundancy_signals(text):
    # Detect potential cognitive redundancy markers
    signals = []
    
    # Check for exact phrase repetition
    if _check_phrase_repetition(text):
        signals.append("Phrase Repetition")
    
    # Check for circular reasoning patterns
    if _detect_circular_reasoning(text):
        signals.append("Circular Logic")
    
    return signals

def _check_phrase_repetition(text):
    # Simple repetition detection
    words = text.lower().split()
    return len(words) > 5 and len(set(words)) < len(words) * 0.6

def _detect_circular_reasoning(text):
    # Basic circular reasoning pattern detection
    circular_patterns = [
        r'because.*because',
        r'therefore.*therefore',
        r'thus.*thus'
    ]
    
    return any(re.search(pattern, text.lower()) for pattern in circular_patterns)

def _generate_adaptive_insight(query, pattern_score, indicators):
    # Generate a nuanced feedback message
    insight_template = (
        "Potential cognitive pattern detected:\n"
        "Complexity Score: {score}\n"
        "Indicators: {indicators}\n"
        "Suggestion: Explore alternative perspectives and linguistic diversity."
    )
    
    return insight_template.format(
        score=pattern_score,
        indicators=", ".join(indicators) if indicators else "None"
    )