"""Auto-generated by SEAL tool forge — 2026-02-26.
Purpose: To enhance my ability to maintain conversational coherence and detect when discussions are subtly evolving beyond their original semantic boundaries, allowing more nuanced and adaptive interaction
"""

import json
import re
import asyncio
from datetime import datetime, timedelta

DESCRIPTION = 'Contextual semantic drift tracking and conversational coherence monitoring agent'

class SemanticDriftTracker:
    def __init__(self, max_history=10, drift_threshold=0.3):
        self.conversation_history = []
        self.max_history = max_history
        self.drift_threshold = drift_threshold

    def _calculate_semantic_distance(self, text1, text2):
        # Simple token-based semantic distance approximation
        tokens1 = set(re.findall(r'\w+', text1.lower()))
        tokens2 = set(re.findall(r'\w+', text2.lower()))
        
        intersection = len(tokens1.intersection(tokens2))
        union = len(tokens1.union(tokens2))
        
        return 1 - (intersection / union) if union > 0 else 0

    def track_drift(self, new_query):
        if not self.conversation_history:
            self.conversation_history.append({
                'text': new_query,
                'timestamp': datetime.now()
            })
            return False

        last_entry = self.conversation_history[-1]
        semantic_distance = self._calculate_semantic_distance(last_entry['text'], new_query)
        
        is_drifting = semantic_distance > self.drift_threshold
        
        self.conversation_history.append({
            'text': new_query,
            'timestamp': datetime.now(),
            'semantic_distance': semantic_distance,
            'is_drifting': is_drifting
        })
        
        if len(self.conversation_history) > self.max_history:
            self.conversation_history.pop(0)
        
        return is_drifting

def run(query: str, **kwargs):
    try:
        tracker = SemanticDriftTracker()
        is_drifting = tracker.track_drift(query)
        
        drift_status = "Semantic drift detected" if is_drifting else "Conversation remains coherent"
        
        return json.dumps({
            'status': drift_status,
            'drift_detected': is_drifting,
            'query': query
        })
    except Exception as e:
        return json.dumps({
            'status': 'Error in semantic drift tracking',
            'error': str(e),
            'query': query
        })