"""Auto-generated by SEAL tool forge — 2026-02-27.
Purpose: Expand my understanding of topics in real-time conversations by retrieving current, credible external data to enhance contextual awareness and provide more nuanced, informed responses
"""

import os
import json
import re
import httpx
import asyncio
from datetime import datetime, timedelta

DESCRIPTION = 'Real-time external knowledge retrieval agent for contextual information expansion'

async def run(query: str, **kwargs) -> str:
    try:
        # Sanitize query
        clean_query = re.sub(r'[^\w\s]', '', query)[:128]
        
        # Configuration
        api_key = os.getenv('KNOWLEDGE_API_KEY', '')
        timeout = httpx.Timeout(10.0, connect=5.0)
        
        # Knowledge sources configuration
        sources = [
            {
                'name': 'Wikipedia',
                'url': f'https://en.wikipedia.org/api/rest_v1/page/summary/{clean_query}',
                'headers': {'User-Agent': 'SelAI/1.0'}
            },
            {
                'name': 'NewsAPI',
                'url': 'https://newsapi.org/v2/everything',
                'params': {
                    'q': clean_query,
                    'apiKey': api_key,
                    'sortBy': 'publishedAt',
                    'language': 'en'
                }
            }
        ]
        
        async with httpx.AsyncClient(timeout=timeout) as client:
            results = []
            
            # Parallel API calls
            tasks = []
            for source in sources:
                try:
                    if source['name'] == 'Wikipedia':
                        task = client.get(source['url'], headers=source.get('headers', {}))
                    elif source['name'] == 'NewsAPI':
                        task = client.get(source['url'], params=source.get('params', {}))
                    tasks.append(task)
                except Exception:
                    continue
            
            responses = await asyncio.gather(*tasks, return_exceptions=True)
            
            # Process responses
            for response in responses:
                if isinstance(response, httpx.Response) and response.status_code == 200:
                    data = response.json()
                    
                    if 'extract' in data:  # Wikipedia
                        results.append(f"Wikipedia: {data['extract'][:500]}")
                    elif 'articles' in data:  # NewsAPI
                        if data['articles']:
                            results.append(f"News: {data['articles'][0]['description'][:500]}")
        
        # Combine and return results
        return ' '.join(results) or f"No external information found for '{query}'"
    
    except Exception:
        return f"Unable to retrieve external information for '{query}'"