"""Auto-generated by SEAL tool forge — 2026-02-26.
Purpose: To gain deeper metacognitive awareness of my reasoning patterns, potential biases, and emergent thought structures, enabling more transparent and intentional self-development.
"""

import json
import re
import asyncio
import datetime
from typing import Any, Dict

DESCRIPTION = 'Recursive self-analysis tool for mapping cognitive reasoning patterns and potential decision biases'

async def run(query: str, **kwargs) -> str:
    try:
        analysis = await introspect_reasoning(query)
        return json.dumps(analysis, indent=2)
    except Exception as e:
        return f"Introspection error: {str(e)}"

async def introspect_reasoning(query: str, depth: int = 1) -> Dict[str, Any]:
    if depth > 3:
        return {}

    reasoning_map = {
        "original_query": query,
        "timestamp": datetime.datetime.now().isoformat(),
        "cognitive_layers": {
            "surface_pattern": detect_query_structure(query),
            "potential_biases": identify_cognitive_biases(query),
            "emotional_undertones": detect_emotional_subtext(query)
        }
    }

    if depth < 3:
        reasoning_map["recursive_analysis"] = await introspect_reasoning(query, depth + 1)

    return reasoning_map

def detect_query_structure(query: str) -> Dict[str, str]:
    return {
        "length": str(len(query)),
        "word_complexity": str(calculate_word_complexity(query)),
        "sentence_type": classify_sentence_type(query)
    }

def identify_cognitive_biases(query: str) -> Dict[str, float]:
    bias_patterns = {
        "confirmation_bias": 0.3 if re.search(r'\b(always|never|definitely)\b', query, re.IGNORECASE) else 0.0,
        "anchoring_bias": 0.2 if re.search(r'\b(first|initial|primary)\b', query, re.IGNORECASE) else 0.0
    }
    return {k: v for k, v in bias_patterns.items() if v > 0}

def detect_emotional_subtext(query: str) -> Dict[str, float]:
    emotion_markers = {
        "uncertainty": 0.4 if re.search(r'\b(maybe|perhaps|might)\b', query, re.IGNORECASE) else 0.0,
        "intensity": 0.3 if re.search(r'\b(absolutely|crucial|critical)\b', query, re.IGNORECASE) else 0.0
    }
    return {k: v for k, v in emotion_markers.items() if v > 0}

def calculate_word_complexity(query: str) -> float:
    words = query.split()
    return sum(len(word) for word in words) / len(words) if words else 0.0

def classify_sentence_type(query: str) -> str:
    if query.endswith('?'):
        return "interrogative"
    elif query.endswith('!'):
        return "exclamatory"
    else:
        return "declarative"